#!/bin/bash
warned=0
final_ret=0

while read oldrev newrev refname; do
    for puppetmodule in `git diff-tree --no-commit-id --name-only -r $newrev`; do
        if [[ "$puppetmodule" =~ ^modules/ ]]; then
          echo "skipping all checks for submodule $puppetmodule"
          continue
        fi

        echo -e "\e[0;36m" "Checking $puppetmodule for science!" "\e[0m"
        tmpdir=`mktemp -d`
        tmpmodule="$tmpdir/$puppetmodule"
        tmperror="$tmpdir/errors.txt"
        mkdir -p $tmpmodule
        rmdir $tmpmodule

        git show $newrev:$puppetmodule > $tmpmodule
        case $puppetmodule in
            *.pp ) 
                /var/lib/gems/1.8/bin/puppet parser validate --storeconfigs true $tmpmodule 2&> $tmperror
                rc=$?
                if [[ $rc != 0 ]]; then
                    echo -e "\e[0;31m'puppet parser validate' failed on $puppetmodule - push denied. Run tests locally and confirm they pass before pushing. \e[0m"
                    cat $tmperror
                    rm -rf $tmpdir
                    final_ret=1
                fi
                # Check styleguide, but do not error if styleguide does not pass
                /var/lib/gems/1.8/bin/puppet-lint --fail-on-warnings --no-80chars-check $tmpmodule > $tmperror
                rc=$?
                if [[ $rc != 0 ]]; then
                    if [[ $warned = 0 ]]; then
                        echo -e "\e[0;31m" "Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html)." "\e[0m"
                        echo -e "\e[0;31m" "The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused." "\e[0m"
                        warned=1
                    fi
                    echo -e "\e[0;33m" "Style guide compliance errors in $puppetmodule:" "\e[0m"
                    echo -e "\e[0;33m"
                    cat $tmperror
                    echo -e "\e[0m"
                fi
                ;;
            *.erb )
                cat $tmpmodule | erb -x -T - | ruby -c > /dev/null 2> $tmperror
                rc=$?
                if [[ $rc != 0 ]]; then
                    echo -e "\e[0;31m" "Ruby syntax checker failed on template $puppetmodule:" "\e[0m"
                    echo -e "\e[0;33m"
                    cat $tmperror
                    echo -e "\e[0m"
                    echo -e "\e[0;33m" "Commit accepted, but the above template will not expand properly" "\e[0m"
                    final_ret=1
                fi
                ;;
        esac
        rm -rf $tmpdir
    done
done

exit $final_ret
